### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by gemini8106**
老師好
我是陳科佑
以下為week1作業
http://52.13.36.155:3000/api/attractions?page=1 
http://52.13.36.155:3000/api/attractions?page=0&keyword=藝術 
http://52.13.36.155:3000/api/attraction/100

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Data format of "images" field should be array, not string.

Fix issue, create new commit, and ask me to review again.

**Comment by gemini8106** [comment]
老師好
我是陳科佑
修改過檔案如下
http://52.13.36.155:3000/api/attractions?page=1
http://52.13.36.155:3000/api/attractions?page=0&keyword=藝術
http://52.13.36.155:3000/api/attraction/100

**Comment by gemini8106** [comment]
老師好
我是陳科佑
以下修改後檔案
http://52.13.36.155:3000/api/attractions?page=1
http://52.13.36.155:3000/api/attractions?page=0&keyword=藝術
http://52.13.36.155:3000/api/attraction/100

**Review by cwpeng — APPROVED** [review]
OK. Done.

Suggestion: use LIMIT statement in your SQL query below and update any related code necessary.
```
cursor.execute("SELECT * FROM attractions WHERE name LIKE concat('%',%s,'%')",(keyword,))
```

**Pull request merged**
